import type { Metadata } from 'next';
import type { Viewport } from 'next';
import { Cairo, Sora } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, getTranslations, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';

import '@/app/globals.css';
import { routing, localeDirection, locales, type Locale } from '@/i18n/routing';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { WhatsAppButton } from '@/components/layout/WhatsAppButton';
import { absoluteUrl, siteUrl } from '@/lib/utils';

/**
 * Sora carries the Latin display/UI voice; Cairo carries Arabic and doubles as
 * the Latin fallback inside Arabic copy, so mixed strings ("EGP 18.5M" in an
 * Arabic sentence) stay on one type colour. Both are self-hosted by next/font
 * and preloaded, so there's no layout shift and no request to Google at runtime.
 */
const sora = Sora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sora',
  weight: ['400', '500', '600', '700', '800'],
});

const cairo = Cairo({
  subsets: ['arabic', 'latin'],
  display: 'swap',
  variable: '--font-cairo',
  weight: ['400', '500', '600', '700', '800'],
});

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#FEFEFE' },
    { media: '(prefers-color-scheme: dark)', color: '#0B1425' },
  ],
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: 'meta.home' });
  const tBrand = await getTranslations({ locale, namespace: 'brand' });

  return {
    metadataBase: new URL(siteUrl()),
    title: {
      default: t('title'),
      // Every child page gets "· Amjad" appended automatically.
      template: `%s · ${tBrand('name')}`,
    },
    description: t('description'),
    applicationName: tBrand('name'),
    authors: [{ name: tBrand('name') }],
    creator: tBrand('name'),
    publisher: tBrand('name'),
    alternates: {
      canonical: absoluteUrl(`/${locale}`),
      languages: {
        ar: absoluteUrl('/ar'),
        en: absoluteUrl('/en'),
        'x-default': absoluteUrl('/ar'),
      },
    },
    openGraph: {
      type: 'website',
      siteName: tBrand('name'),
      title: t('title'),
      description: t('description'),
      url: absoluteUrl(`/${locale}`),
      locale: locale === 'ar' ? 'ar_EG' : 'en_US',
      alternateLocale: locale === 'ar' ? 'en_US' : 'ar_EG',
      // `images` is intentionally omitted: Next injects the card generated by
      // ./opengraph-image.tsx, with its correct hashed URL. Hardcoding a path
      // here would only go stale.
    },
    twitter: {
      card: 'summary_large_image',
      title: t('title'),
      description: t('description'),
    },
    robots: {
      index: true,
      follow: true,
      googleBot: { index: true, follow: true, 'max-image-preview': 'large' },
    },
    // `icons` is intentionally omitted: Next picks up app/icon.png (a 256px
    // mark on a navy tile, generated by `npm run logo:assets`). Pointing at the
    // master logo.png here would ship a ~900kb favicon.
    formatDetection: { telephone: false },
  };
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  // Opts this subtree into static rendering — without it every page using
  // translations would silently become dynamic.
  setRequestLocale(locale);

  const messages = await getMessages();
  const dir = localeDirection[locale as Locale];

  return (
    <html
      lang={locale}
      dir={dir}
      className={`${sora.variable} ${cairo.variable}`}
      suppressHydrationWarning
    >
      <body className="min-h-dvh bg-sand-50 antialiased">
        <NextIntlClientProvider messages={messages}>
          <Header />
          <main id="main" className="min-h-dvh">
            {children}
          </main>
          <Footer />
          <WhatsAppButton />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
