import type { Agent, Property } from './types';

/**
 * Bundled demo portfolio.
 *
 * This is what the site serves until a Sanity project is connected, so a fresh
 * clone looks complete on first `npm run dev`. `scripts/seed.ts` pushes these
 * same records (and uploads the images) into Sanity, so the demo content and
 * the CMS content are the same portfolio.
 */

const img = (file: string, altAr: string, altEn: string) => ({
  url: `/images/properties/${file}.jpg`,
  alt: { ar: altAr, en: altEn },
});

// ── Advisors ───────────────────────────────────────────────────────────────

const mariam: Agent = {
  name: { ar: 'مريم زكي', en: 'Mariam Zaki' },
  role: { ar: 'رئيسة الاستثمار', en: 'Head of Investment' },
  phone: '+20 100 111 2020',
  whatsapp: '201001112020',
  email: 'mariam@amjad-developments.com',
};

const yousef: Agent = {
  name: { ar: 'يوسف درويش', en: 'Yousef Darwish' },
  role: { ar: 'المؤسس والشريك الإداري', en: 'Founder & Managing Partner' },
  phone: '+20 100 111 3030',
  whatsapp: '201001113030',
  email: 'yousef@amjad-developments.com',
};

const salma: Agent = {
  name: { ar: 'سلمى نور', en: 'Salma Nour' },
  role: { ar: 'رئيسة محافظ العملاء', en: 'Head of Client Portfolio' },
  phone: '+20 100 111 4040',
  whatsapp: '201001114040',
  email: 'salma@amjad-developments.com',
};

export const demoAgents: Agent[] = [mariam, yousef, salma];

// ── Portfolio ──────────────────────────────────────────────────────────────

export const demoProperties: Property[] = [
  {
    _id: 'demo-rise-gardens-villa-12',
    slug: 'rise-gardens-villa-12',
    title: { ar: 'فيلا 12 — حدائق أمجد', en: 'Amjad Gardens Villa 12' },
    description: {
      ar: 'فيلا مستقلة على قطعة ركنية داخل حدائق أمجد، المشروع الذي سلَّمناه عام 2016 قبل موعده بأحد عشر أسبوعاً. أربع غرف نوم، جميعها بحمّامات خاصة، ومساحة معيشة مزدوجة الارتفاع تُطل على حديقة خاصة بمساحة 180 متراً. الوحدة مؤجَّرة حالياً بعائد 9.4% ويمكن تسليمها فارغة أو بعقد قائم.',
      en: 'A detached villa on a corner plot inside Amjad Gardens — the compound we delivered eleven weeks early back in 2016. Four bedrooms, all en-suite, with a double-height living space opening onto a private 180 m² garden. Currently tenanted at a 9.4% yield; available vacant or with the lease in place.',
    },
    type: 'villa',
    status: 'for-sale',
    price: 18500000,
    bedrooms: 4,
    bathrooms: 5,
    area: 520,
    location: {
      city: { ar: 'القاهرة الجديدة', en: 'New Cairo' },
      district: { ar: 'حدائق أمجد، التجمع الخامس', en: 'Amjad Gardens, Fifth Settlement' },
      lat: 30.0074,
      lng: 31.4913,
    },
    gallery: [
      img('villa-1', 'واجهة فيلا 12 الأمامية وحمام السباحة والحديقة', 'The front elevation of Villa 12, with the pool and garden'),
      img('interior-1', 'غرفة المعيشة مزدوجة الارتفاع', 'The double-height living room'),
      img('villa-2', 'فناء داخلي بحمام سباحة ونخلة', 'The inner courtyard, with its pool and palm'),
      img('interior-2', 'المطبخ المفتوح على منطقة الطعام', 'The open kitchen and dining area'),
    ],
    features: [
      { ar: 'حديقة خاصة 180 م²', en: 'Private 180 m² garden' },
      { ar: 'حمّام خاص لكل غرفة', en: 'All bedrooms en-suite' },
      { ar: 'معيشة مزدوجة الارتفاع', en: 'Double-height living space' },
      { ar: 'نظام منزل ذكي', en: 'Smart home system' },
      { ar: 'جراج مغطى لسيارتين', en: 'Covered parking for two' },
      { ar: 'مؤجَّرة حالياً بعائد 9.4%', en: 'Tenanted at 9.4% yield' },
    ],
    featured: true,
    reference: 'RISE-V-112',
    agent: mariam,
    publishedAt: '2025-06-02T09:00:00.000Z',
  },
  {
    _id: 'demo-marina-crest-penthouse',
    slug: 'marina-crest-penthouse',
    title: { ar: 'بنتهاوس مارينا كريست', en: 'Marina Crest Penthouse' },
    description: {
      ar: 'الطابق الأخير بالكامل في مارينا كريست، بواجهة زجاجية ممتدة من الأرض إلى السقف تطل على البحر مباشرة وتراس بمساحة 140 متراً مع حمام سباحة خاص. سعر المتر هنا ارتفع 31% خلال ثلاث سنوات، وهو الأصل الأعلى أداءً في محفظة الساحل لدينا.',
      en: 'The entire top floor of Marina Crest, with a floor-to-ceiling glass frontage facing straight out to sea and a 140 m² terrace with a private pool. Price per metre here is up 31% in three years, making it the strongest performer in our North Coast book.',
    },
    type: 'penthouse',
    status: 'for-sale',
    price: 42000000,
    bedrooms: 4,
    bathrooms: 5,
    area: 380,
    location: {
      city: { ar: 'الساحل الشمالي', en: 'North Coast' },
      district: { ar: 'سيدي عبد الرحمن', en: 'Sidi Abdel Rahman' },
      lat: 30.9585,
      lng: 28.81,
    },
    gallery: [
      img('penthouse-1', 'صالة البنتهاوس بواجهة زجاجية على البحر', 'The penthouse lounge with its sea-facing glass wall'),
      img('penthouse-2', 'التراس وحمام السباحة الخاص', 'The terrace and private pool'),
      img('interior-3', 'غرفة النوم الرئيسية', 'The principal bedroom'),
      img('penthouse-3', 'منظر البحر عند الغروب من التراس', 'The sea view from the terrace at sunset'),
    ],
    features: [
      { ar: 'طابق كامل بمدخل خاص', en: 'Full floor, private lift entry' },
      { ar: 'حمام سباحة خاص على التراس', en: 'Private terrace pool' },
      { ar: 'واجهة زجاجية على البحر', en: 'Full-height sea-facing glazing' },
      { ar: 'تراس 140 م²', en: '140 m² terrace' },
      { ar: 'تشطيب كامل ومفروش', en: 'Fully finished and furnished' },
      { ar: 'غرفة خدمة منفصلة', en: 'Separate staff quarters' },
    ],
    featured: true,
    reference: 'RISE-P-204',
    agent: yousef,
    publishedAt: '2025-05-18T09:00:00.000Z',
  },
  {
    _id: 'demo-the-vertex-tower',
    slug: 'the-vertex-tower-3br',
    title: { ar: 'برج فيرتكس — شقة 3 غرف', en: 'The Vertex Tower — 3 Bedroom' },
    description: {
      ar: 'شقة على الخارطة في برج فيرتكس، التسليم في الربع الثاني من 2027. خطة سداد على ثماني سنوات بمقدَّم 10%، وهي أطول خطة نُقدِّمها. الطوابق من 12 إلى 18 لها إطلالة مفتوحة لا يمكن البناء أمامها — تحقَّقنا من ذلك في المخطط التفصيلي قبل أن نشتري الأرض.',
      en: 'An off-plan unit in The Vertex, handing over Q2 2027. Eight-year payment plan at 10% down — the longest we offer. Floors 12 to 18 have a protected open view; we checked the master plan before we bought the land.',
    },
    type: 'apartment',
    status: 'off-plan',
    price: 6800000,
    bedrooms: 3,
    bathrooms: 3,
    area: 185,
    location: {
      city: { ar: 'القاهرة الجديدة', en: 'New Cairo' },
      district: { ar: 'التجمع الخامس', en: 'Fifth Settlement' },
      lat: 30.0131,
      lng: 31.4256,
    },
    gallery: [
      img('tower-1', 'برج فيرتكس من الخارج', 'The Vertex tower exterior'),
      img('tower-2', 'الواجهة الزجاجية للبرج', 'The tower glass façade'),
      img('interior-4', 'تصوّر لغرفة المعيشة بعد التشطيب', 'Render of the finished living room'),
    ],
    features: [
      { ar: 'خطة سداد 8 سنوات، مقدَّم 10%', en: '8-year plan, 10% down' },
      { ar: 'التسليم الربع الثاني 2027', en: 'Handover Q2 2027' },
      { ar: 'إطلالة مفتوحة محمية', en: 'Protected open view' },
      { ar: 'جيم ومسبح مشترك', en: 'Shared gym and pool' },
      { ar: 'أمن على مدار الساعة', en: '24/7 security' },
    ],
    featured: true,
    reference: 'RISE-A-318',
    agent: mariam,
    publishedAt: '2025-06-20T09:00:00.000Z',
  },
  {
    _id: 'demo-palm-court-townhouse',
    slug: 'palm-court-townhouse-6',
    title: { ar: 'تاون هاوس 6 — بالم كورت', en: 'Palm Court Townhouse 6' },
    description: {
      ar: 'تاون هاوس أوسط داخل كمبوند بالم كورت المسوَّر، على مسافة مشي من النادي والمنطقة التجارية. أربع غرف نوم على طابقين، وحديقة خلفية 90 متراً. رسوم الصيانة هنا 38 جنيهاً للمتر سنوياً — من الأقل في الشيخ زايد، وهو ما يجعل صافي العائد أفضل مما يبدو من السعر.',
      en: 'A mid-terrace townhouse inside the gated Palm Court compound, walking distance from the clubhouse and retail strip. Four bedrooms over two floors and a 90 m² rear garden. Service charge is 38 EGP/m²/year — among the lowest in Sheikh Zayed, which makes the net yield better than the headline price suggests.',
    },
    type: 'townhouse',
    status: 'for-sale',
    price: 12200000,
    bedrooms: 4,
    bathrooms: 4,
    area: 310,
    location: {
      city: { ar: 'الشيخ زايد', en: 'Sheikh Zayed' },
      district: { ar: 'كمبوند بالم كورت', en: 'Palm Court Compound' },
      lat: 30.0778,
      lng: 30.9756,
    },
    gallery: [
      // Cover first: a building among the planting reads as a home. The aerial
      // courtyard that follows is landscaping, so it is described as such.
      img('compound-2', 'إحدى وحدات بالم كورت وسط النخيل', 'One of the Palm Court units, among the palms'),
      img('compound-1', 'الفناء المشترك والنخيل من أعلى', 'The shared courtyard and palms, from above'),
      img('interior-2', 'المطبخ ومنطقة الطعام', 'The kitchen and dining area'),
    ],
    features: [
      { ar: 'كمبوند مسوَّر بأمن 24 ساعة', en: 'Gated, 24-hour security' },
      { ar: 'حديقة خلفية 90 م²', en: '90 m² rear garden' },
      { ar: 'رسوم صيانة منخفضة', en: 'Low service charge' },
      { ar: 'نادٍ ومنطقة تجارية بمسافة مشي', en: 'Clubhouse and retail on foot' },
      { ar: 'مسارات مشي ومناطق خضراء', en: 'Walking trails and green space' },
    ],
    featured: false,
    reference: 'RISE-T-406',
    agent: salma,
    publishedAt: '2025-04-11T09:00:00.000Z',
  },
  {
    _id: 'demo-zamalek-residence-401',
    slug: 'zamalek-residence-401',
    title: { ar: 'زمالك ريزيدنس 401', en: 'Zamalek Residence 401' },
    description: {
      ar: 'شقة مفروشة بالكامل في مبنى من الثلاثينيات على شارع هادئ في الزمالك، بعد ترميم كامل احتفظ بالأرضيات الخشبية الأصلية والأسقف المرتفعة. تُؤجَّر عادةً لعقود سنوية للسلك الدبلوماسي؛ متاحة الآن بعد انتهاء عقد مدته ثلاث سنوات.',
      en: 'A fully furnished apartment in a 1930s building on a quiet Zamalek street, after a full restoration that kept the original parquet and high ceilings. It usually lets on annual contracts to the diplomatic community; available now after a three-year tenancy ended.',
    },
    type: 'apartment',
    status: 'for-rent',
    price: 65000,
    bedrooms: 3,
    bathrooms: 2,
    area: 210,
    location: {
      city: { ar: 'القاهرة', en: 'Cairo' },
      district: { ar: 'الزمالك', en: 'Zamalek' },
      lat: 30.0614,
      lng: 31.2197,
    },
    gallery: [
      img('apartment-1', 'غرفة الاستقبال بأسقفها المرتفعة', 'The reception room and its high ceilings'),
      img('apartment-2', 'غرفة النوم الرئيسية', 'The principal bedroom'),
      img('apartment-3', 'الشرفة المطلة على الشارع', 'The street-facing balcony'),
    ],
    features: [
      { ar: 'مفروشة بالكامل', en: 'Fully furnished' },
      { ar: 'مبنى تاريخي مُرمَّم', en: 'Restored heritage building' },
      { ar: 'أرضيات باركيه أصلية', en: 'Original parquet floors' },
      { ar: 'أسقف بارتفاع 3.6 م', en: '3.6 m ceilings' },
      { ar: 'مصعد وبوّاب', en: 'Lift and doorman' },
    ],
    featured: false,
    reference: 'RISE-A-401',
    agent: salma,
    publishedAt: '2025-06-28T09:00:00.000Z',
  },
  {
    _id: 'demo-rise-business-park',
    slug: 'rise-business-park-floor-7',
    title: { ar: 'أمجد بيزنس بارك — الطابق السابع', en: 'Amjad Business Park — Floor 7' },
    description: {
      ar: 'طابق مكتبي كامل بمساحة مفتوحة وواجهة زجاجية على محورين، جاهز للتقسيم حسب احتياج المستأجر. المبنى حاصل على شهادة LEED الفضية، وتكلفة التشغيل فيه أقل بنحو 22% من متوسط المنطقة — وهو الفارق الذي يهمّ فعلاً في عقد لخمس سنوات.',
      en: 'A full open-plan office floor with glazing on two elevations, ready to be partitioned to the tenant\'s spec. The building is LEED Silver certified and runs about 22% below the district average on operating cost — which is the number that actually matters across a five-year lease.',
    },
    type: 'office',
    status: 'for-rent',
    price: 180000,
    bedrooms: 0,
    bathrooms: 2,
    area: 450,
    location: {
      city: { ar: 'القاهرة الجديدة', en: 'New Cairo' },
      district: { ar: 'التسعين الشمالي، التجمع الخامس', en: '90th Street North, Fifth Settlement' },
      lat: 30.0261,
      lng: 31.4703,
    },
    gallery: [
      img('office-1', 'المساحة المكتبية المفتوحة', 'The open-plan office floor'),
      img('office-2', 'ردهة الاستقبال في المبنى', 'The building reception lobby'),
      img('tower-3', 'واجهة أمجد بيزنس بارك', 'The Amjad Business Park façade'),
    ],
    features: [
      { ar: 'طابق مفتوح قابل للتقسيم', en: 'Open plan, partition-ready' },
      { ar: 'شهادة LEED الفضية', en: 'LEED Silver certified' },
      { ar: 'واجهة زجاجية على محورين', en: 'Dual-aspect glazing' },
      { ar: 'مولّد احتياطي كامل', en: 'Full backup generator' },
      { ar: '12 موقف سيارات مخصص', en: '12 dedicated parking bays' },
      { ar: 'ألياف بصرية مزدوجة المزوّد', en: 'Dual-provider fibre' },
    ],
    featured: true,
    reference: 'RISE-O-507',
    agent: yousef,
    publishedAt: '2025-05-30T09:00:00.000Z',
  },
  {
    _id: 'demo-lagoon-chalet-27',
    slug: 'lagoon-chalet-27',
    title: { ar: 'شاليه 27 — لاجون', en: 'Lagoon Chalet 27' },
    description: {
      ar: 'شاليه في الصف الأول على البحيرة في العين السخنة، على بعد ساعتين من القاهرة. ثلاث غرف نوم وتراس يفتح مباشرة على الماء. الوحدة ضمن برنامج الإيجار قصير الأجل لدينا، ويُحقِّق حالياً 7.1% صافياً بعد الرسوم — وهو رقم واقعي لأصل موسمي، لا وعد بعشرة بالمئة.',
      en: 'A front-row lagoon chalet in Ain Sokhna, two hours from Cairo. Three bedrooms and a terrace that opens straight onto the water. It sits in our short-let programme and currently returns 7.1% net of fees — a realistic number for a seasonal asset, not a promised ten.',
    },
    type: 'chalet',
    status: 'for-sale',
    price: 9400000,
    bedrooms: 3,
    bathrooms: 3,
    area: 165,
    location: {
      city: { ar: 'العين السخنة', en: 'Ain Sokhna' },
      district: { ar: 'منتجع لاجون', en: 'Lagoon Resort' },
      lat: 29.6,
      lng: 32.3167,
    },
    gallery: [
      img('chalet-1', 'الشاليه من ناحية البحيرة', 'The chalet seen from the lagoon'),
      img('chalet-2', 'التراس المطل على الماء', 'The waterside terrace'),
    ],
    features: [
      { ar: 'الصف الأول على البحيرة', en: 'Front-row lagoon position' },
      { ar: 'تراس مباشر على الماء', en: 'Terrace onto the water' },
      { ar: 'ضمن برنامج الإيجار قصير الأجل', en: 'In our short-let programme' },
      { ar: 'مفروش بالكامل', en: 'Fully furnished' },
      { ar: 'ساعتان من القاهرة', en: 'Two hours from Cairo' },
    ],
    featured: false,
    reference: 'RISE-C-627',
    agent: salma,
    publishedAt: '2025-03-22T09:00:00.000Z',
  },
  {
    _id: 'demo-the-aurora-villa',
    slug: 'the-aurora-villa',
    title: { ar: 'فيلا أورورا', en: 'The Aurora Villa' },
    description: {
      ar: 'أكبر أصل في محفظتنا السكنية: 780 متراً مبنية على قطعة 1,450 متراً، بخمس غرف نوم وحمام سباحة لا نهائي وشقة ضيوف مستقلة. صُمِّمت مع معماري واحد على مدى أربعة عشر شهراً، ومُواصفاتها موضوعة لمالكٍ يبقى ثلاثين عاماً لا لصور الافتتاح.',
      en: 'The largest asset in our residential book: 780 m² built on a 1,450 m² plot, with five bedrooms, an infinity pool and a self-contained guest apartment. Designed with a single architect over fourteen months, and specified for the thirty-year owner rather than the launch photography.',
    },
    type: 'villa',
    status: 'for-sale',
    price: 55000000,
    bedrooms: 5,
    bathrooms: 6,
    area: 780,
    location: {
      city: { ar: 'الشيخ زايد', en: 'Sheikh Zayed' },
      district: { ar: 'بيفرلي هيلز', en: 'Beverly Hills' },
      lat: 30.0503,
      lng: 30.9631,
    },
    gallery: [
      img('villa-3', 'فيلا أورورا وحمام السباحة ومنطقة الجلوس الخارجية', 'The Aurora Villa, its pool and the outdoor lounge'),
      img('villa-4', 'حمام السباحة اللانهائي وقت الغروب بإطلالة على حافة الصحراء', 'The infinity pool at sunset, looking out over the desert edge'),
      img('interior-1', 'الصالة الرئيسية', 'The main reception'),
      img('interior-3', 'جناح النوم الرئيسي', 'The principal bedroom suite'),
    ],
    features: [
      { ar: 'قطعة أرض 1,450 م²', en: '1,450 m² plot' },
      { ar: 'حمام سباحة لا نهائي', en: 'Infinity pool' },
      { ar: 'شقة ضيوف مستقلة', en: 'Self-contained guest apartment' },
      { ar: 'تصميم معماري خاص', en: 'Bespoke architectural design' },
      { ar: 'أتمتة منزلية كاملة', en: 'Full home automation' },
      { ar: 'جراج لأربع سيارات', en: 'Four-car garage' },
      { ar: 'ألواح شمسية', en: 'Solar array' },
    ],
    featured: true,
    reference: 'RISE-V-801',
    agent: yousef,
    publishedAt: '2025-07-01T09:00:00.000Z',
  },
  {
    _id: 'demo-nile-vista-apartment',
    slug: 'nile-vista-apartment',
    title: { ar: 'شقة نايل فيستا', en: 'Nile Vista Apartment' },
    description: {
      ar: 'شقة في المعادي بإطلالة جانبية على النيل من الشرفة الرئيسية، في مبنى هادئ من ست وحدات فقط. سعر المتر في هذا الشارع تحديداً أقل بـ 14% من متوسط المعادي الساحلي، وهو فارق نراه يُغلق تدريجياً منذ افتتاح المحور الجديد.',
      en: 'A Maadi apartment with a side Nile view from the main balcony, in a quiet six-unit building. Price per metre on this particular street runs 14% below the Corniche Maadi average — a gap we\'ve watched narrow since the new axis opened.',
    },
    type: 'apartment',
    status: 'for-sale',
    price: 8900000,
    bedrooms: 3,
    bathrooms: 2,
    area: 195,
    location: {
      city: { ar: 'القاهرة', en: 'Cairo' },
      district: { ar: 'المعادي', en: 'Maadi' },
      lat: 29.9603,
      lng: 31.257,
    },
    gallery: [
      img('interior-4', 'غرفة المعيشة', 'The living room'),
      img('apartment-2', 'غرفة النوم الرئيسية', 'The principal bedroom'),
      img('interior-3', 'الشرفة المطلة على النيل', 'The Nile-facing balcony'),
    ],
    features: [
      { ar: 'إطلالة جانبية على النيل', en: 'Side Nile view' },
      { ar: 'مبنى من ست وحدات فقط', en: 'Six-unit building' },
      { ar: 'شرفتان', en: 'Two balconies' },
      { ar: 'موقف سيارة مخصص', en: 'Dedicated parking' },
      { ar: 'قريبة من المدارس الدولية', en: 'Near international schools' },
    ],
    featured: false,
    reference: 'RISE-A-903',
    agent: salma,
    publishedAt: '2025-02-14T09:00:00.000Z',
  },
  {
    _id: 'demo-sokhna-land-a7',
    slug: 'sokhna-land-plot-a7',
    title: { ar: 'قطعة أرض A7 — السخنة', en: 'Sokhna Land Plot A7' },
    description: {
      ar: 'قطعة أرض 1,200 متر برخصة بناء سارية حتى 2028، على بعد 400 متر من البحر ضمن امتداد مُخطَّط له بالكامل. مناسبة لمن يريد أن يبني بمواصفاته لا أن يشتري ما بناه غيره. مرافق كاملة على حدود القطعة، والملكية مسجَّلة ومُتحقَّق منها.',
      en: 'A 1,200 m² plot with a build permit valid to 2028, 400 m from the sea inside a fully master-planned extension. For the buyer who wants to build to their own spec rather than inherit someone else\'s. Utilities are at the plot boundary and the title is registered and verified.',
    },
    type: 'land',
    status: 'for-sale',
    price: 4200000,
    area: 1200,
    location: {
      city: { ar: 'العين السخنة', en: 'Ain Sokhna' },
      district: { ar: 'الامتداد الشمالي', en: 'Northern Extension' },
      lat: 29.6142,
      lng: 32.3389,
    },
    gallery: [
      img('land-1', 'قطعة الأرض والمنطقة المحيطة بها', 'The plot and its surroundings'),
    ],
    features: [
      { ar: 'رخصة بناء سارية حتى 2028', en: 'Build permit valid to 2028' },
      { ar: '400 م من البحر', en: '400 m from the sea' },
      { ar: 'مرافق على حدود القطعة', en: 'Utilities at the boundary' },
      { ar: 'ملكية مسجَّلة ومُتحقَّق منها', en: 'Registered, verified title' },
      { ar: 'ضمن مخطَّط عام معتمد', en: 'Inside an approved master plan' },
    ],
    featured: false,
    reference: 'RISE-L-A07',
    agent: yousef,
    publishedAt: '2025-01-19T09:00:00.000Z',
  },
  {
    _id: 'demo-boulevard-retail-unit',
    slug: 'boulevard-retail-unit-14',
    title: { ar: 'وحدة تجارية 14 — البوليفارد', en: 'Boulevard Retail Unit 14' },
    description: {
      ar: 'وحدة تجارية بواجهة زجاجية على ممر البوليفارد، بحركة مشاة مُقاسة تبلغ 4,800 شخص يومياً في المتوسط خلال أيام الأسبوع. مؤجَّرة سابقاً لسلسلة مقاهٍ لمدة خمس سنوات؛ التجهيزات الكهربائية والصرف الخاصة بالمطاعم قائمة بالفعل، وهو ما يوفّر على المستأجر التالي قرابة نصف مليون في التجهيز.',
      en: 'A glass-fronted retail unit on the Boulevard walkway, with measured footfall averaging 4,800 a day on weekdays. Previously let to a coffee chain for five years; the F&B power and drainage provisions are already in, which saves the next tenant roughly half a million in fit-out.',
    },
    type: 'retail',
    status: 'for-rent',
    price: 95000,
    bathrooms: 1,
    area: 120,
    location: {
      city: { ar: 'القاهرة الجديدة', en: 'New Cairo' },
      district: { ar: 'ممشى البوليفارد، التجمع الخامس', en: 'The Boulevard, Fifth Settlement' },
      lat: 30.0189,
      lng: 31.4361,
    },
    gallery: [
      img('retail-1', 'الوحدة التجارية وواجهتها الزجاجية على الممشى', 'The retail unit and its glass frontage on the walkway'),
    ],
    features: [
      { ar: 'واجهة زجاجية على الممشى', en: 'Glass frontage on the walkway' },
      { ar: 'حركة مشاة 4,800 يومياً', en: '4,800 daily footfall' },
      { ar: 'تجهيزات مطاعم قائمة', en: 'F&B provisions already in' },
      { ar: 'مخزن خلفي', en: 'Rear storage' },
      { ar: 'لافتة على الواجهة الرئيسية', en: 'Primary frontage signage' },
    ],
    featured: false,
    reference: 'RISE-R-014',
    agent: mariam,
    publishedAt: '2025-04-27T09:00:00.000Z',
  },
];
